---
title: "Paper figures - circuit models"
output: html_notebook
---

# Libraries and helpers
```{r helper_fns, echo=FALSE, fig.width=6, fig.height=4, echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)
library(readr)
library(dplyr)
library(png)
library(psd)
library(tidyr)
library(patchwork)
library(bspec)
```

# Load data
```{r load1, message=FALSE, warning=FALSE, error=FALSE}
# -- num_pop search-----------------------------------------------------------
# dMI (choose stim_rate, sweep g)
# stim_rates <- c('1', '2', '3', '4')
stim_rates <- c("0.5", "1", "1.5", "2.0", "2.5", "3.0")
num_pops <- c('40', '80', '160', '320', '640', '1280', '2560', '5120', '10240')

# exp4
# path <- "~/Code/theagamma/data/exp4/"
path <- "~/Code/theagamma/data/exp41/"
dmi_exp4 <- NULL
for(stim_rate in stim_rates){
  for (num_pop in num_pops) {
    file_name <-
      paste(
        path,
        "sample",
        stim_rate,
        "_",
        num_pop,
        "_dMI.csv",
        sep = ""
      )
    df <- read.csv(file_name)
    df$stim_rate <- as.numeric(stim_rate)
    df$model <- "ING"
    dmi_exp4 <- bind_rows(df, dmi_exp4)
  }
}
dl2_exp4 <- NULL
for(stim_rate in stim_rates){
  for (num_pop in num_pops) {
    file_name <-
      paste(
        path,
        "sample",
        stim_rate,
        "_",
        num_pop,
        "_dl2.csv",
        sep = ""
      )
    df <- read.csv(file_name)
    df$stim_rate <- as.numeric(stim_rate)
    df$model <- "ING"
    dl2_exp4 <- bind_rows(df, dl2_exp4)
  }
}

# exp5
# path <- "~/Code/theagamma/data/exp5/"
path <- "~/Code/theagamma/data/exp42/"
dmi_exp5 <- NULL
for(stim_rate in stim_rates){
  for (num_pop in num_pops) {
    file_name <-
      paste(
        path,
        "sample",
        stim_rate,
        "_",
        num_pop,
        "_dMI.csv",
        sep = ""
      )
    df <- read.csv(file_name)
    df$stim_rate <- as.numeric(stim_rate)
    df$model <- "PING"
    dmi_exp5 <- bind_rows(df, dmi_exp5)
  }
}
dl2_exp5 <- NULL
for(stim_rate in stim_rates){
  for (num_pop in num_pops) {
    file_name <-
      paste(
        path,
        "sample",
        stim_rate,
        "_",
        num_pop,
        "_dl2.csv",
        sep = ""
      )
    df <- read.csv(file_name)
    df$stim_rate <- as.numeric(stim_rate)
    df$model <- "PING"
    dl2_exp5 <- bind_rows(df, dl2_exp5)
  }
}

# exp6
# path <- "~/Code/theagamma/data/exp6/"
path <- "~/Code/theagamma/data/exp43/"
dmi_exp6 <- NULL
for(stim_rate in stim_rates){
  for (num_pop in num_pops) {
    file_name <-
      paste(
        path,
        "sample",
        stim_rate,
        "_",
        num_pop,
        "_dMI.csv",
        sep = ""
      )
    df <- read.csv(file_name)
    df$stim_rate <- as.numeric(stim_rate)
    df$model <- "CHING"
    dmi_exp6 <- bind_rows(df, dmi_exp6)
  }
}
dl2_exp6 <- NULL
for(stim_rate in stim_rates){
  for (num_pop in num_pops) {
    file_name <-
      paste(
        path,
        "sample",
        stim_rate,
        "_",
        num_pop,
        "_dl2.csv",
        sep = ""
      )
    df <- read.csv(file_name)
    df$stim_rate <- as.numeric(stim_rate)
    df$model <- "CHING"
    dl2_exp6 <- bind_rows(df, dl2_exp6)
  }
}


# -- num_pop = big and small 
# ING
gs <- c('3', '3.5', '4', '4.5', '5', '5.5', '6.0', '6.5', '7.0')
stim_rates <- c('0.5', '1', '1.5', '2.0', '2.5', '3.0')
num_pops <- c('1280', '10240')

# path <- "~/Code/theagamma/data/exp18/"
path <- "~/Code/theagamma/data/exp53/"
dmi_exp18 <- NULL
for(g in gs){
  for(stim_rate in stim_rates){
    for (num_pop in num_pops) {
      file_name <-
        paste(path,
              "sample-g",
              g,
              "-s",
              stim_rate,
              "_",
              num_pop,
              "_dMI.csv",
              sep = "")
      df <- read.csv(file_name)
      df$g <- as.numeric(g)
      df$stim_rate <- as.numeric(stim_rate)
      df$model <- "ING"
      df$g_code <- "g_I"
      dmi_exp18 <- bind_rows(df, dmi_exp18)
    }
  }
}

# PING - g_ei
gs <- c('0.6', '0.7', '0.8', '0.9', '1.0', '1.1', '1.2', '1.3', '1.4')
stim_rates <- c('0.5', '1', '1.5', '2.0', '2.5', '3.0')
num_pops <- c('1280', '10240')

# path <- "~/Code/theagamma/data/exp20/"
path <- "~/Code/theagamma/data/exp55/"
dmi_exp20 <- NULL
for(g in gs){
  for(stim_rate in stim_rates){
    for (num_pop in num_pops) {
      file_name <-
        paste(path,
              "sample-g",
              g,
              "-s",
              stim_rate,
              "_",
              num_pop,
              "_dMI.csv",
              sep = "")
      df <- read.csv(file_name)
      df$g <- as.numeric(g)
      df$stim_rate <- as.numeric(stim_rate)
      df$model <- "PING"
      df$g_code <- "g_EI"
      dmi_exp20 <- bind_rows(df, dmi_exp20)
    }
  }
}

# PING - g_ie
gs <- c('3', '3.5', '4', '4.5', '5', '5.5', '6.0', '6.5', '7.0') 
stim_rates <- c('0.5', '1', '1.5', '2.0', '2.5', '3.0')
num_pops <- c('1280', '10240')

# path <- "~/Code/theagamma/data/exp22/"
path <- "~/Code/theagamma/data/exp57/"
dmi_exp22 <- NULL
for(g in gs){
  for(stim_rate in stim_rates){
    for (num_pop in num_pops) {
      file_name <-
        paste(path,
              "sample-g",
              g,
              "-s",
              stim_rate,
              "_",
              num_pop,
              "_dMI.csv",
              sep = "")
      df <- read.csv(file_name)
      df$g <- as.numeric(g)
      df$stim_rate <- as.numeric(stim_rate)
      df$model <- "PING"
      df$g_code <- "g_IE"
      dmi_exp22 <- bind_rows(df, dmi_exp22)
    }
  }
}

# CHING - g_e
gs <- c('0.6', '0.7', '0.8', '0.9', '1.0', '1.1', '1.2', '1.3', '1.4')
stim_rates <- c('0.5', '1', '1.5', '2.0', '2.5', '3.0')
num_pops <- c('160', '10240')

# path <- "~/Code/theagamma/data/exp24/"
path <- "~/Code/theagamma/data/exp59/"
dmi_exp24 <- NULL
for(g in gs){
  for(stim_rate in stim_rates){
    for (num_pop in num_pops) {
      file_name <-
        paste(path,
              "sample-g",
              g,
              "-s",
              stim_rate,
              "_",
              num_pop,
              "_dMI.csv",
              sep = "")
      df <- read.csv(file_name)
      df$g <- as.numeric(g)
      df$stim_rate <- as.numeric(stim_rate)
      df$model <- "CHING"
      df$g_code <- "g_E"
      dmi_exp24 <- bind_rows(df, dmi_exp24)
    }
  }
}

# TAU ------------------------------------------------------------
# ING
taus <- c('5', '5.2', '5.3', '5.4', '5.6', '5.8', '6', '6.2', '6.4')
stim_rates <- c('0.5', '1', '1.5', '2.0', '2.5', '3.0')
num_pops <- c('1280', '10240')
# exp45
path <- "~/Code/theagamma/data/exp45/"
dmi_exp45 <- NULL
for(g in taus){
  for(stim_rate in stim_rates){
    for (num_pop in num_pops) {
      file_name <-
        paste(path,
              "sample-t",
              g,
              "-s",
              stim_rate,
              "_",
              num_pop,
              "_dMI.csv",
              sep = "")
      df <- read.csv(file_name)
      df$g <- as.numeric(g)
      df$stim_rate <- as.numeric(stim_rate)
      dmi_exp45 <- bind_rows(df, dmi_exp45)
    }
  }
}

# PING - t_E
taus <- c('1', '1.2', '1.3', '1.4', '1.6', '1.8', '2', '2.2', '2.4')
stim_rates <- c('0.5', '1', '1.5', '2.0', '2.5', '3.0')
num_pops <- c('1280', '10240')

path <- "~/Code/theagamma/data/exp47/"
dmi_exp47 <- NULL
for(g in taus){
  for(stim_rate in stim_rates){
    for (num_pop in num_pops) {
      file_name <-
        paste(path,
              "sample-t",
              g,
              "-s",
              stim_rate,
              "_",
              num_pop,
              "_dMI.csv",
              sep = "")
      df <- read.csv(file_name)
      df$g <- as.numeric(g)
      df$stim_rate <- as.numeric(stim_rate)
      dmi_exp47 <- bind_rows(df, dmi_exp47)
    }
  }
}

# PING - t_I
taus <- c('6.5', '6.75', '7.0', '7.25', '7.5', '7.75', '8.0', '8.25', '8.5')
stim_rates <- c('0.5', '1', '1.5', '2.0', '2.5', '3.0')
num_pops <- c('1280', '10240')

path <- "~/Code/theagamma/data/exp49/"
dmi_exp49 <- NULL
for(g in taus){
  for(stim_rate in stim_rates){
    for (num_pop in num_pops) {
      file_name <-
        paste(path,
              "sample-t",
              g,
              "-s",
              stim_rate,
              "_",
              num_pop,
              "_dMI.csv",
              sep = "")
      df <- read.csv(file_name)
      df$g <- as.numeric(g)
      df$stim_rate <- as.numeric(stim_rate)
      dmi_exp49 <- bind_rows(df, dmi_exp49)
    }
  }
}

# CHING = t_E
taus <- c('4.0', '4.25', '4.5', '4.75', '5', '5.25', '5.5', '5.75', '6.0')
stim_rates <- c('0.5', '1', '1.5', '2.0', '2.5', '3.0')
num_pops <- c('160', '10240')

# exp51
path <- "~/Code/theagamma/data/exp51/"
dmi_exp51 <- NULL
for(g in taus){
  for(stim_rate in stim_rates){
    for (num_pop in num_pops) {
      file_name <-
        paste(path,
              "sample-t",
              g,
              "-s",
              stim_rate,
              "_",
              num_pop,
              "_dMI.csv",
              sep = "")
      df <- read.csv(file_name)
      df$g <- as.numeric(g)
      df$stim_rate <- as.numeric(stim_rate)
      dmi_exp51 <- bind_rows(df, dmi_exp51)
    }
  }
}

# EXAMPLES ------------------------------------------------------------
ref1 <- read_csv("../data/test_ing_ref.csv")
stim1 <- read_csv("../data/test_ing_stim.csv")
ing1 <- read_csv("../data/test_ing_osc.csv")
ing2 <- read_csv("../data/test_ing_oscspks.csv")
ing3 <- read_csv("../data/test_ing_spec.csv")
ping1 <- read_csv("../data/test_ping_osc.csv")
ping2 <- read_csv("../data/test_ping_oscspks.csv")
ping3 <- read_csv("../data/test_ping_spec.csv")
ching1 <- read_csv("../data/test_ching_osc.csv")
ching2 <- read_csv("../data/test_ching_oscspks.csv")
ching3 <- read_csv("../data/test_ching_spec.csv")
```


# Figure - Examples 
```{r, fig.width=10, fig.height=7, echo=FALSE, warning=FALSE, message=FALSE}
# -- S
ref1 %>%
  ggplot(aes(x = times, y = rate)) +
  geom_line(color = "darkgrey", size = 1.1) +
  scale_y_continuous(breaks = c(0, 0.5, 1), limits = c(0, 1)) +
  theme_classic() +
  labs(x = "",
       y = "Norm. rate",
       tag = "a.",
       title = "Stimulus") +
  theme(plot.title = element_text(size = 9, face = "bold")) ->
  s1

ref1 %>%
  select(rate) %>%
  welchPSD(seglength = 10000) -> spec
spec <- data.frame(frequency = spec$frequency * 10000,
                   power = spec$power)
spec %>%
  filter(frequency < 60) %>%
  ggplot(aes(x = frequency, y = log10(power))) +
  geom_line(size = 1, color = "darkgrey") +
  labs(x = "", y = "Power") +
  lims(y = c(-3, 2)) +
  theme_classic() +
  theme(plot.title = element_text(size = 9, face = "bold")) -> p1


# -- ING
ing1 %>%
  filter(times > 0.25) %>%
  ggplot(aes(x = times, y = rate)) +
  geom_line(size = 1.2) +
  theme_classic() +
  labs(x = "", y = "Rate (spk/s)", title = "ING") +
  theme(plot.title = element_text(size = 9, face = "bold")) -> s2

ing2 %>%
  filter(ns <= 10240) %>%
  ggplot(aes(x = ts, y = ns)) +
  geom_point(size = 0.2) +
  theme_classic() +
  labs(x = "", y = "N") +
  lims(x = c(2, 3)) +
  theme(plot.title = element_text(size = 9, face = "bold")) -> k2

ing3 %>%
  filter(freq < 60) %>%
  ggplot(aes(x = freq, y = spectrum)) +
  geom_line(size = 0.8) +
  labs(x = "", y = "Power") +
  theme_classic() +
  theme(plot.title = element_text(size = 9, face = "bold")) -> p2

# -- PING
ping1 %>%
  filter(times > 0.25) %>%
  ggplot(aes(x = times, y = rate)) +
  geom_line(size = 1.2) +
  theme_classic() +
  labs(x = "", y = "Rate (spk/s)", title = "PING") +
  theme(plot.title = element_text(size = 9, face = "bold")) -> s3

ping2 %>%
  filter(ns <= 10240) %>%
  ggplot(aes(x = ts, y = ns)) +
  geom_point(size = 0.2) +
  theme_classic() +
  labs(x = "", y = "N") +
  lims(x = c(2, 3)) +
  theme(plot.title = element_text(size = 9, face = "bold")) -> k3

ping3 %>%
  filter(freq < 60) %>%
  ggplot(aes(x = freq, y = spectrum)) +
  geom_line(size = 0.8) +
  labs(x = "", y = "Power") +
  theme_classic() +
  theme(plot.title = element_text(size = 9, face = "bold")) -> p3

# -- CHING
ching1 %>%
  filter(times > 0.25) %>%
  ggplot(aes(x = times, y = rate)) +
  geom_line(size = 1.2) +
  theme_classic() +
  labs(x = "Time (s)",
       y = "Rate (spk/s)",
       title = "CHING") +
  theme(plot.title = element_text(size = 9, face = "bold")) -> s4

ching2 %>%
  filter(ns <= 10240) %>%
  ggplot(aes(x = ts, y = ns)) +
  geom_point(size = 0.02) +
  theme_classic() +
  labs(x = "Time (s)", y = "N") +
  lims(x = c(2, 3)) +
  theme(plot.title = element_text(size = 9, face = "bold")) -> k4

ching3 %>%
  filter(freq < 60) %>%
  ggplot(aes(x = freq, y = spectrum)) +
  geom_line(size = 0.8) +
  labs(x = "Frequency (Hz)", y = "Power") +
  theme_classic() +
  theme(plot.title = element_text(size = 9, face = "bold")) -> p4

# Build --------------------------------------------------------------------  
layout <- "
AAA###B
CCCDDDE
FFFGGGH
IIIJJJK
"
s1 + p1 + s2 + k2 + p2 + s3 + k3 + p3 + s4 + k4 + p4 +
  plot_annotation(
    tag_levels = 'a',
    tag_suffix = "."
  ) +
plot_layout(design = layout)

ggsave(
  "figures/circuit_example.pdf",
  dpi = 300,
  width = 10,
  height = 7
)
ggsave(
  "figures/circuit_example.png",
  dpi = 300,
  width = 10,
  height = 7
)
```

# Figure - num_pop - circuit 1 
```{r, fig.width=8, fig.height=3, echo=FALSE, warning=FALSE, message=FALSE}
tmp1 <- NULL
tmp1 <- bind_rows(dmi_exp4, tmp1)
tmp1 <- bind_rows(dmi_exp5, tmp1)
tmp1 <- bind_rows(dmi_exp6, tmp1)
tmp1$model <- factor(tmp1$model, levels=c("ING", "PING", "CHING"))

# -----------------------------------------------
# Jitter all
tmp1 %>% 
  filter(stim_rate == 1) %>%
  ggplot(aes(x=model, y=E)) +
  geom_jitter(size=.1, alpha=0.4, width=0.3) +
  stat_summary(aes(group=model), fun.y=mean,
               geom="point", colour="black", alpha=1, size=14, shape="_") +
  geom_hline(yintercept=0, color="dark grey", size=0.5) + xlab("") +
  labs(y=expression(paste(Delta, "MI (bits)")), x="Model", title="") +
  theme_classic() + 
  theme(plot.title = element_text(size = 7, hjust=3, face = "bold")) -> 
  p1
# print(p1)

# -----------------------------------------------
# Num. pop. sequence
tmp1 %>%
  filter(stim_rate == 1) %>%
  group_by(model, num_pop) %>%
  summarise(M=mean(E),
            SD=sd(E)) -> 
  tmp2
tmp2$model <- factor(tmp2$model, levels=c("ING", "PING", "CHING"))

tmp2 %>% 
  ggplot(aes(x=as.numeric(num_pop), y=M)) +
  geom_line(size=0.7, alpha=1) +
  geom_ribbon(aes(ymin=M-SD, ymax=M+SD), alpha=0.2, color=NA) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  scale_x_log10() +
  annotation_logticks(sides="b") + 
  labs(y=expression(paste(Delta, "MI (bits)")), x="Population size") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_text(face = "bold")) +
  facet_grid(.~model) ->
  p2
print(p2)

# -----------------------------------------------
# Build figure
p1 + p2 + plot_layout(widths = c(0.2, 0.8)) +
  plot_annotation(tag_levels = 'a', tag_suffix = ".")
ggsave("figures/circuit1.pdf", dpi=300, width = 8, height = 3)
ggsave("figures/circuit1.png", dpi=300, width = 8, height = 3)
```

# Figure - small - stim/g
```{r, fig.width=9, fig.height=7, echo=FALSE, warning=FALSE, message=FALSE}
tmp1 <- NULL
tmp1 <- bind_rows(dmi_exp18, tmp1)
tmp1 <- bind_rows(dmi_exp20, tmp1)
tmp1 <- bind_rows(dmi_exp22, tmp1)
tmp1 <- bind_rows(dmi_exp24, tmp1)
tmp1$model <- factor(tmp1$model, levels=c("ING", "PING", "CHING"))

# -----------------------------------------------
# Jitter all
tmp %>% 
  filter(num_pop < 10240) %>% 
  ggplot(aes(x=model, y=E)) +
  geom_jitter(size=0.8, alpha=0.4, width=0.25) +
  stat_summary(aes(group=model), fun.y=mean,
               geom="point", colour="black", alpha=1, size=15, shape="_") +
  geom_hline(yintercept=0, color="dark grey", size=0.5) + xlab("") +
  labs(y=expression(paste(Delta, "MI (bits)")), x="Model", title="") +
  theme_classic() + 
  theme(plot.title = element_text(size = 7, hjust=3, face = "bold")) -> 
  p1
print(p1)

# -----------------------------------------------
## stim_rate sequence

tmp1 %>%
  group_by(model, num_pop, g_code, g, stim_rate) %>%
  summarise(M=mean(E),
            SD=sd(E)) -> 
  tmp2
tmp2$model <- factor(tmp2$model, levels=c("ING", "PING", "CHING"))

# ING
tmp2 %>% 
  filter(num_pop < 10240) %>% 
  filter(model == "ING") %>% 
  ggplot(aes(x=stim_rate,  y=M, color=factor(g), group=factor(g))) +
  geom_line(size=1.5, alpha=1) +
  geom_ribbon(aes(
    ymin = M - SD,
    ymax = M + SD,
    fill = factor(g)
  ),
  alpha = 0.2,
  color = NA) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  labs(y = expression(paste(Delta, "MI (bits)")),
       x = "Stimulus firing rate (spks/s)",
       title = "ING") +
  lims(y=c(-0.8, 0.3)) +
  scale_color_manual(expression(g[I]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  scale_fill_manual(expression(g[I]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(legend.position = "bottom") +
  theme(plot.title = element_text(size = 11, face = "bold")) +
  theme(strip.text.x = element_text(face = "bold")) ->
  p2

print(p2)

# ING - EI
tmp2 %>% 
  filter(num_pop < 10240) %>% 
  filter(model == "PING") %>% 
  filter(g_code == "g_EI") %>% 
  ggplot(aes(x=stim_rate,  y=M, color=factor(g), group=factor(g))) +
  geom_line(size=1.5, alpha=1) +
  geom_ribbon(aes(
    ymin = M - SD,
    ymax = M + SD,
    fill = factor(g)
  ),
  alpha = 0.2,
  color = NA) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  # scale_x_continuous(breaks=c(5,10,15,20,15,20,25,30)) +
  labs(y = expression(paste(Delta, "MI (bits)")),
       x = "Stimulus firing rate (spks/s)",
       title = "PING (E to I)") +
  lims(y=c(-0.8, 0.3)) +
  scale_color_manual(expression(g[EI]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  scale_fill_manual(expression(g[EI]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(legend.position = "bottom") +
  theme(plot.title = element_text(size = 11, face = "bold")) +
  theme(strip.text.x = element_text(face = "bold")) ->
  p3
print(p3)

# ING - IE
tmp2 %>% 
  filter(num_pop < 10240) %>% 
  filter(model == "PING") %>% 
  filter(g_code == "g_IE") %>% 
  ggplot(aes(x=stim_rate,  y=M, color=factor(g), group=factor(g))) +
  geom_line(size=1.5, alpha=1) +
  geom_ribbon(aes(
    ymin = M - SD,
    ymax = M + SD,
    fill = factor(g)
  ),
  alpha = 0.2,
  color = NA) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  # scale_x_continuous(breaks=c(5,10,15,20,15,20,25,30)) +
  labs(y = expression(paste(Delta, "MI (bits)")),
       x = "Stimulus firing rate (spks/s)",
       title = "PING (I to E)") +
  lims(y=c(-0.8, 0.3)) +
  scale_color_manual(expression(g[IE]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  scale_fill_manual(expression(g[IE]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(legend.position = "bottom") +
  theme(plot.title = element_text(size = 11, face = "bold")) +
  theme(strip.text.x = element_text(face = "bold")) ->
  p4
print(p4)

# ING - IE
tmp2 %>% 
  filter(num_pop < 10240) %>% 
  filter(model == "CHING") %>% 
  # filter(g_code == "g_E") %>% 
  ggplot(aes(x=stim_rate,  y=M, color=factor(g), group=factor(g))) +
  geom_line(size=1.5, alpha=1) +
  geom_ribbon(aes(
    ymin = M - SD,
    ymax = M + SD,
    fill = factor(g)
  ),
  alpha = 0.2,
  color = NA) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  # scale_x_continuous(breaks=c(5,10,15,20,15,20,25,30)) +
  labs(y = expression(paste(Delta, "MI (bits)")),
       x = "Stimulus firing rate (spks/s)",
       title = "CHING") +
  lims(y=c(-0.8, 0.3)) +
  scale_color_manual(expression(g[E]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  scale_fill_manual(expression(g[E]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(legend.position = "bottom") +
  theme(panel.spacing = unit(1, "lines")) +
  theme(plot.title = element_text(size = 11, face = "bold")) +
  theme(strip.text.x = element_text(face = "bold")) ->
  p5
print(p5)


# -----------------------------------------------
# Build figure
layout <- "
AABBBCCC
AABBBCCC
##DDDEEE
##DDDEEE
"

p1 + p2 + p5 + p3 + p4 +
  plot_annotation(
    tag_levels = 'a',
    tag_suffix = ".",
    title = "Population size: 160 or 1280",
    theme = theme(plot.title = element_text(size = 11, face = "bold"))
  ) +
  plot_layout(design = layout)
ggsave(
  "figures/circuit2.pdf",
  dpi = 300,
  width = 9,
  height = 8
)
ggsave(
  "figures/circuit2.png",
  dpi = 300,
  width = 9,
  height = 8
)
```

### Sig test results 
- For the paper.
```{r}
# compare_means(mi~model, tmp,  p.adjust.method = "bonf")
```

# Figure - large - circuit 3 
```{r, fig.width=9, fig.height=8, echo=FALSE, warning=FALSE, message=FALSE}
tmp1 <- NULL
tmp1 <- bind_rows(dmi_exp18, tmp1)
tmp1 <- bind_rows(dmi_exp20, tmp1)
tmp1 <- bind_rows(dmi_exp22, tmp1)
tmp1 <- bind_rows(dmi_exp24, tmp1)
tmp1$model <- factor(tmp1$model, levels=c("ING", "PING", "CHING"))

# -----------------------------------------------
# Jitter all
tmp %>% 
  filter(num_pop == 10240) %>% 
  ggplot(aes(x=model, y=E)) +
  geom_jitter(size=0.8, alpha=0.4, width=0.25) +
  stat_summary(aes(group=model), fun.y=mean,
               geom="point", colour="black", alpha=1, size=16, shape="_") +
  geom_hline(yintercept=0, color="dark grey", size=0.5) + xlab("") +
  labs(y=expression(paste(Delta, "MI (bits)")), x="Model", title="") +
  theme_classic() + 
  theme(plot.title = element_text(size = 7, hjust=3, face = "bold")) -> 
  p1
# print(p1)

# -----------------------------------------------
## stim_rate sequence

tmp1 %>%
  group_by(model, num_pop, g_code, g, stim_rate) %>%
  summarise(M=mean(E),
            SD=sd(E)) -> 
  tmp2
tmp2$model <- factor(tmp2$model, levels=c("ING", "PING", "CHING"))

# ING
tmp2 %>% 
  filter(num_pop == 10240) %>% 
  filter(model == "ING") %>% 
  ggplot(aes(x=stim_rate,  y=M, color=factor(g), group=factor(g))) +
  geom_line(size=1.5, alpha=1) +
  geom_ribbon(aes(
    ymin = M - SD,
    ymax = M + SD,
    fill = factor(g)
  ),
  alpha = 0.2,
  color = NA) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  labs(y = expression(paste(Delta, "MI (bits)")),
       x = "Stimulus firing rate (spks/s)",
       title = "ING") +
  lims(y=c(-0.8, 0.3)) +
  scale_color_manual(expression(g[I]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  scale_fill_manual(expression(g[I]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(legend.position = "bottom") +
  theme(plot.title = element_text(size = 11, face = "bold")) +
  theme(strip.text.x = element_text(face = "bold")) ->
  p2
# print(p2)

# ING - EI
tmp2 %>% 
  filter(num_pop == 10240) %>% 
  filter(model == "PING") %>% 
  filter(g_code == "g_EI") %>% 
  ggplot(aes(x=stim_rate,  y=M, color=factor(g), group=factor(g))) +
  geom_line(size=1.5, alpha=1) +
  geom_ribbon(aes(
    ymin = M - SD,
    ymax = M + SD,
    fill = factor(g)
  ),
  alpha = 0.2,
  color = NA) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  # scale_x_continuous(breaks=c(5,10,15,20,15,20,25,30)) +
  labs(y = expression(paste(Delta, "MI (bits)")),
       x = "Stimulus firing rate (spks/s)",
       title = "PING (E to I)") +
  lims(y=c(-0.8, 0.3)) +
  scale_color_manual(expression(g[EI]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  scale_fill_manual(expression(g[EI]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(legend.position = "bottom") +
  theme(plot.title = element_text(size = 11, face = "bold")) +
  theme(strip.text.x = element_text(face = "bold")) ->
  p3
# print(p3)

# ING - IE
tmp2 %>% 
  filter(num_pop == 10240) %>% 
  filter(model == "PING") %>% 
  filter(g_code == "g_IE") %>% 
  ggplot(aes(x=stim_rate,  y=M, color=factor(g), group=factor(g))) +
  geom_line(size=1.5, alpha=1) +
  geom_ribbon(aes(
    ymin = M - SD,
    ymax = M + SD,
    fill = factor(g)
  ),
  alpha = 0.2,
  color = NA) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  # scale_x_continuous(breaks=c(5,10,15,20,15,20,25,30)) +
  labs(y = expression(paste(Delta, "MI (bits)")),
       x = "Stimulus firing rate (spks/s)",
       title = "PING (I to E)") +
  lims(y=c(-0.8, 0.3)) +
  scale_color_manual(expression(g[IE]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  scale_fill_manual(expression(g[IE]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(legend.position = "bottom") +
  theme(plot.title = element_text(size = 11, face = "bold")) +
  theme(strip.text.x = element_text(face = "bold")) ->
  p4
# print(p4)

# ING - IE
tmp2 %>% 
  filter(num_pop == 10240) %>% 
  filter(model == "CHING") %>% 
  # filter(g_code == "g_E") %>% 
  ggplot(aes(x=stim_rate,  y=M, color=factor(g), group=factor(g))) +
  geom_line(size=1.5, alpha=1) +
  geom_ribbon(aes(
    ymin = M - SD,
    ymax = M + SD,
    fill = factor(g)
  ),
  alpha = 0.2,
  color = NA) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  # scale_x_continuous(breaks=c(5,10,15,20,15,20,25,30)) +
  labs(y = expression(paste(Delta, "MI (bits)")),
       x = "Stimulus firing rate (spks/s)",
       title = "CHING") +
  lims(y=c(-0.8, 0.3)) +
  scale_color_manual(expression(g[E]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  scale_fill_manual(expression(g[E]), values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(legend.position = "bottom") +
  theme(panel.spacing = unit(1, "lines")) +
  theme(plot.title = element_text(size = 11, face = "bold")) +
  theme(strip.text.x = element_text(face = "bold")) ->
  p5
print(p5)


# -----------------------------------------------
# Build figure
layout <- "
AABBBCCC
AABBBCCC
##DDDEEE
##DDDEEE
"

p1 + p2 + p5 + p3 + p4 + 
  plot_annotation(
    tag_levels = 'a',
    tag_suffix = ".",
    title = "Population size: 10240",
    theme = theme(plot.title = element_text(size = 11, face = "bold"))
  ) +
  plot_layout(design = layout)
ggsave("figures/circuit3.pdf", dpi=300, width = 9, height = 8)
ggsave("figures/circuit3.png", dpi=300, width = 9, height = 8)
```

# Figure - tau (large and small)
```{r, fig.width=4, fig.height=8, echo=FALSE, warning=FALSE, message=FALSE}
# ING
dmi_exp45 %>%
  filter(stim_rate == 1) %>%
  group_by(num_pop, g) %>%
  summarise(M=mean(E),
            SD=sd(E)) -> 
  tmp

tmp %>% 
  filter(num_pop >= 40) %>% 
  ggplot(aes(x=g, y=M)) +
  # geom_jitter() +
  geom_line(size=0.7, alpha=1) +
  geom_ribbon(aes(ymin=M-SD, ymax=M+SD), alpha=0.2, color=NA) +
  geom_hline(yintercept=0, color="grey") + xlab("") +
  labs(y = expression(paste(Delta, "MI (bits)")),
       x = expression(tau[I]),
       # title = "Model: PING (E)") +
       title=expression(paste("ING - all ", tau[I]))) +
  lims(y = c(-0.3, 0.3)) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_text(face = "bold")) +
  theme(plot.title = element_text(size = 11, face = "bold")) +
  scale_color_manual("", values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  facet_grid(.~num_pop) -> tt1

# PING 
dmi_exp47 %>%
  filter(stim_rate == 1) %>%
  group_by(num_pop, g) %>%
  summarise(M=mean(E),
            SD=sd(E)) -> 
  tmp

tmp %>% 
  filter(num_pop >= 40) %>% 
  ggplot(aes(x=g, y=M)) +
  # geom_jitter() +
  geom_line(size=0.7, alpha=1) +
  geom_ribbon(aes(ymin=M-SD, ymax=M+SD), alpha=0.2, color=NA) +
  geom_hline(yintercept=0, color="grey") + xlab("") +
  labs(y = expression(paste(Delta, "MI (bits)")),
       x = expression(tau[E]),
       # title = "Model: PING (E)") +
       title=expression(paste("PING - all ", tau[E]))) +
  lims(y = c(-0.3, 0.3)) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_text(face = "bold")) +
  theme(plot.title = element_text(size = 11, face = "bold")) +
  scale_color_manual("", values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  facet_grid(.~num_pop) -> tt2

dmi_exp49 %>%
  filter(stim_rate == 1) %>%
  group_by(num_pop, g) %>%
  summarise(M=mean(E),
            SD=sd(E)) -> 
  tmp

tmp %>% 
  filter(num_pop >= 40) %>% 
  ggplot(aes(x=g, y=M)) +
  # geom_jitter() +
  geom_line(size=0.7, alpha=1) +
  geom_ribbon(aes(ymin=M-SD, ymax=M+SD), alpha=0.2, color=NA) +
  geom_hline(yintercept=0, color="grey") + xlab("") +
  labs(y = expression(paste(Delta, "MI (bits)")),
       x = expression(tau[I]),
       # title = "Model: PING (E)") +
       title=expression(paste("PING - all ", tau[I]))) +
  lims(y = c(-0.3, 0.3)) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_text(face = "bold")) +
  theme(plot.title = element_text(size = 11, face = "bold")) +
  scale_color_manual("", values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  facet_grid(.~num_pop) -> tt3

dmi_exp51 %>%
  filter(stim_rate == 1) %>%
  group_by(num_pop, g) %>%
  summarise(M=mean(E),
            SD=sd(E)) -> 
  tmp

tmp %>% 
  filter(num_pop >= 40) %>% 
  ggplot(aes(x=g, y=M)) +
  # geom_jitter() +
  geom_line(size=0.7, alpha=1) +
  geom_ribbon(aes(ymin=M-SD, ymax=M+SD), alpha=0.2, color=NA) +
  geom_hline(yintercept=0, color="grey") + xlab("") +
  labs(y = expression(paste(Delta, "MI (bits)")),
       x = expression(tau[E]),
       # title = "Model: PING (E)") +
       title=expression(paste("CHING - all ", tau[E]))) +
  lims(y = c(-0.3, 0.3)) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_text(face = "bold")) +
  theme(plot.title = element_text(size = 10, face = "bold")) +
  scale_color_manual("", values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "slateblue4",
    "mediumpurple4",
    "darkorchid4"
    )) +
  facet_grid(.~num_pop) -> tt4

tt1 / tt2 / tt3 / tt4 +
  plot_annotation(
    tag_levels = 'a',
    tag_suffix = "."
  )
ggsave(
  "figures/circuit4.pdf",
  dpi = 300,
  width = 4,
  height = 8
)
ggsave(
  "figures/circuit4.png",
  dpi = 300,
  width = 4,
  height = 8
)
```

# Figure - error (pop_size) 
Supp. 
```{r, fig.width=8, fig.height=3, echo=FALSE, warning=FALSE, message=FALSE}
tmp1 <- NULL
tmp1 <- bind_rows(dl2_exp4, tmp1)
tmp1 <- bind_rows(dl2_exp5, tmp1)
tmp1 <- bind_rows(dl2_exp6, tmp1)
tmp1$model <- factor(tmp1$model, levels=c("ING", "PING", "CHING"))

# tmp1$E <- minmax_scaler(tmp1$E, -1, 1)
# -----------------------------------------------
# Jitter all
tmp1 %>% 
  filter(stim_rate == 1) %>%
  ggplot(aes(x=model, y=E)) +
  geom_jitter(size=.1, alpha=0.4, width=0.3) +
  stat_summary(aes(group=model), fun.y=mean,
               geom="point", colour="black", alpha=1, size=14, shape="_") +
  geom_hline(yintercept=0, color="dark grey", size=0.5) + xlab("") +
  labs(y="Total error", x="Model", title="") +
  theme_classic() + 
  theme(plot.title = element_text(size = 7, hjust=3, face = "bold")) -> 
  p1
# print(p1)

# -----------------------------------------------
# Num. pop. sequence
tmp1 %>%
  filter(stim_rate == 1) %>%
  group_by(model, num_pop) %>%
  summarise(M=mean(E),
            SD=sd(E)) -> 
  tmp2
tmp2$model <- factor(tmp2$model, levels=c("ING", "PING", "CHING"))

tmp2 %>% 
  ggplot(aes(x=as.numeric(num_pop), y=M)) +
  geom_line(size=0.7, alpha=1) +
  geom_ribbon(aes(ymin=M-SD, ymax=M+SD), alpha=0.2, color=NA) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  scale_x_log10() +
  annotation_logticks(sides="b") + 
  labs(y="Total error", x="Population size") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_text(face = "bold")) +
  facet_grid(.~model) ->
  p2
print(p2)

# -----------------------------------------------
# Build figure
p1 + p2 + plot_layout(widths = c(0.2, 0.8)) +
  plot_annotation(tag_levels = 'a', tag_suffix = ".")
ggsave("figures/circuit5.pdf", dpi=300, width = 8, height = 3)
ggsave("figures/circuit5.png", dpi=300, width = 8, height = 3)
```
