---
title: "Analysis - average, best, worst - many exps"
output: html_notebook
---

# Aim
I have looking at mean dMI. It is interesting to also look at the min/max. These are the best/worst costs and so could be very relevant?

# Libs
```{r helper_fns, echo=FALSE, fig.width=6, fig.height=4, echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)
library(readr)
library(dplyr)
library(png)
library(psd)
library(tidyr)
library(patchwork)
```

# Load data
```{r helper_fns, echo=FALSE, fig.width=6, fig.height=4, echo=FALSE, warning=FALSE, message=FALSE}
# -- num_pop search-----------------------------------------------------------
stim_rates <- c("0.5", "1", "1.5", "2.0", "2.5", "3.0")
num_pops <- c('40', '80', '160', '320', '640', '1280', '2560', '5120', '10240')

# ING
# path <- "~/Code/theagamma/data/exp4/"
path <- "~/Code/theagamma/data/exp41/"
dmi_exp4 <- NULL
for(stim_rate in stim_rates){
  for (num_pop in num_pops) {
    file_name <-
      paste(
        path,
        "sample",
        stim_rate,
        "_",
        num_pop,
        "_dMI.csv",
        sep = ""
      )
    df <- read.csv(file_name)
    df$stim_rate <- as.numeric(stim_rate)
    df$model <- "ING"
    dmi_exp4 <- bind_rows(df, dmi_exp4)
  }
}

# PING
# path <- "~/Code/theagamma/data/exp5/"
path <- "~/Code/theagamma/data/exp42/"
dmi_exp5 <- NULL
for(stim_rate in stim_rates){
  for (num_pop in num_pops) {
    file_name <-
      paste(
        path,
        "sample",
        stim_rate,
        "_",
        num_pop,
        "_dMI.csv",
        sep = ""
      )
    df <- read.csv(file_name)
    df$stim_rate <- as.numeric(stim_rate)
    df$model <- "PING"
    dmi_exp5 <- bind_rows(df, dmi_exp5)
  }
}

# CHING
# path <- "~/Code/theagamma/data/exp6/"
path <- "~/Code/theagamma/data/exp43/"
dmi_exp6 <- NULL
for(stim_rate in stim_rates){
  for (num_pop in num_pops) {
    file_name <-
      paste(
        path,
        "sample",
        stim_rate,
        "_",
        num_pop,
        "_dMI.csv",
        sep = ""
      )
    df <- read.csv(file_name)
    df$stim_rate <- as.numeric(stim_rate)
    df$model <- "CHING"
    dmi_exp6 <- bind_rows(df, dmi_exp6)
  }
}
```

# Join data
```{r}
tmp1 <- NULL
tmp1 <- bind_rows(dmi_exp4, tmp1)
tmp1 <- bind_rows(dmi_exp5, tmp1)
tmp1 <- bind_rows(dmi_exp6, tmp1)
tmp1$model <- factor(tmp1$model, levels=c("ING", "PING", "CHING"))
```

# Avg
```{r, fig.width=8.6, fig.height=2.4, echo=FALSE, warning=FALSE, message=FALSE}
tmp1 %>% 
  filter(stim_rate == 1) %>%
  ggplot(aes(x=model, y=E)) +
  geom_jitter(size=.1, alpha=0.4, width=0.3) +
  stat_summary(aes(group=model), fun.y=mean,
               geom="point", colour="black", alpha=1, size=14, shape="_") +
  geom_hline(yintercept=0, color="dark grey", size=0.5) + 
  labs(title="Average case", y=expression(paste(Delta, "MI (bits)")), x="Model") +
  theme_classic() + 
  theme(plot.title = element_text(size = 9, face = "bold")) -> 
  p1

tmp1 %>%
  filter(stim_rate == 1) %>%
  group_by(model, num_pop) %>%
  summarise(M=mean(E),
            SD=sd(E)) -> 
  tmp2
tmp2$model <- factor(tmp2$model, levels=c("ING", "PING", "CHING"))

tmp2 %>% 
  ggplot(aes(x=as.numeric(num_pop), y=M)) +
  geom_line(size=0.7, alpha=1) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  scale_x_log10() +
  annotation_logticks(sides="b") + 
  labs(y=expression(paste(Delta, "MI (bits)")), x="Population size") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_text(face = "bold")) +
  facet_grid(.~model) ->
  p2

# --------------------------------------------------------------
## Build Figure
r1 <- p1 + p2 + plot_layout(widths = c(0.2, 0.8)) 
print(r1)
```

# min
```{r, fig.width=8.6, fig.height=2.4, echo=FALSE, warning=FALSE, message=FALSE}
tmp1 %>% 
  filter(stim_rate == 1) %>%
  ggplot(aes(x=model, y=E)) +
  geom_jitter(size=.1, alpha=0.4, width=0.3) +
  stat_summary(aes(group=model), fun.y=min,
               geom="point", colour="black", alpha=1, size=14, shape="_") +
  geom_hline(yintercept=0, color="dark grey", size=0.5) + xlab("") +
  labs(y=expression(paste(Delta, "MI (bits)")), x="Model", title="Worst case") +
  theme_classic() + 
  theme(plot.title = element_text(size = 9, face = "bold")) -> 
  p3
tmp1 %>%
  filter(stim_rate == 1) %>%
  group_by(model, num_pop) %>%
  summarise(M=min(E)) -> 
  tmp2
tmp2$model <- factor(tmp2$model, levels=c("ING", "PING", "CHING"))

tmp2 %>% 
  ggplot(aes(x=as.numeric(num_pop), y=M)) +
  geom_line(size=0.7, alpha=1) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  scale_x_log10() +
  annotation_logticks(sides="b") + 
  labs(y=expression(paste(Delta, "MI (bits)")), x="Population size") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_text(face = "bold")) +
  facet_grid(.~model) ->
  p4

# --------------------------------------------------------------
## Build Figure
r2 <- p3 + p4 + plot_layout(widths = c(0.2, 0.8)) 
print(r2)
```

```{r, fig.width=8.6, fig.height=2.4, echo=FALSE, warning=FALSE, message=FALSE}
tmp1 %>% 
  filter(stim_rate == 1) %>%
  ggplot(aes(x=model, y=E)) +
  geom_jitter(size=.1, alpha=0.4, width=0.3) +
  stat_summary(aes(group=model), fun.y=max,
               geom="point", colour="black", alpha=1, size=14, shape="_") +
  geom_hline(yintercept=0, color="dark grey", size=0.5) + xlab("") +
  labs(y=expression(paste(Delta, "MI (bits)")), x="Model", title="Best case") +
  theme_classic() + 
  theme(plot.title = element_text(size = 9, face = "bold")) -> p5
tmp1 %>%
  filter(stim_rate == 1) %>%
  group_by(model, num_pop) %>%
  summarise(M=max(E)) -> 
  tmp2
tmp2$model <- factor(tmp2$model, levels=c("ING", "PING", "CHING"))

tmp2 %>% 
  ggplot(aes(x=as.numeric(num_pop), y=M)) +
  geom_line(size=0.7, alpha=1) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  scale_x_log10() +
  annotation_logticks(sides="b") + 
  labs(y=expression(paste(Delta, "MI (bits)")), x="Population size") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_text(face = "bold")) +
  facet_grid(.~model) -> p6

# --------------------------------------------------------------
## Build Figure
r3 <- p5 + p6 + plot_layout(widths = c(0.2, 0.8)) 
print(r3)
```


# joint plot
```{r, fig.width=8, fig.height=7, echo=FALSE, warning=FALSE, message=FALSE}
## Build Figure
r1 / r2 / r3 +
  plot_annotation(tag_levels = 'a', tag_suffix = ".",
                  # title="Population size: 1",
                  theme=theme(plot.title = element_text(size = 13, face = "bold")))

ggsave(
  "figures/circuit-extrema1.pdf",
  dpi = 300,
  width = 8,
  height = 7
)
ggsave(
  "figures/circuit-extrema1.png",
  dpi = 300,
  width = 8,
  height = 7
)
```